import numpy as np


# 1. Calculate the total revenue generated by two product categories in a store
# Input: category1_revenue = np.array([500, 600, 700, 550]) 
#        category2_revenue = np.array([450, 700, 800, 600])
# Output: Total Revenue: [ 950 1300 1500 1150]
category1_revenue = np.array([500,600,700,550])
category2_revenue = np.array([450,700,800,600])
total_revenue = category1_revenue + category2_revenue
print("Total Revenue:",total_revenue)


# 2. Calculate the profit made by a company
# Input: revenue = np.array([10000, 12000, 11000, 10500])
#        expenses = np.array([4000, 5000, 4500, 4800])
# Output: Profit: [6000 7000 6500 5700]
revenue = np.array([10000,12000,11000,10500])
expenses = np.array([4000,5000,4500,4800])
profit = revenue - expenses
print("Profit:",profit)


# 3. Determine which products in a store are out of stock (quantity is 0).
# Input: inventory = np.array([10, 0, 5, 0, 20, 0])
# Output: Out of Stock Products: [0 0 0]
import numpy as np

inventory = np.array([10, 0, 5, 0, 20, 0])
zero_indices = np.where(inventory == 0)
print("Out of Stock Products:", inventory[zero_indices])


# 4. Calculate the total cost of items in a shopping cart, considering the quantity and price per item.
# Input: quantity = np.array([2, 3, 4, 1])
#        price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
# Output: Total Cost of Items: [20. 15. 32. 12.]
quantity = np.array([2,3,4,1])
price_per_item = np.array([10.0,5.0,8.0,12.0])
print("Total Cost of items:",quantity*price_per_item)